wandb_version: 1

dataset:
  desc: null
  value:
    channel_type:
    - InF_Los
    - InF_Nlos
    - InH_Los
    - InH_Nlos
    - RMa_Los
    - RMa_Nlos
    - UMa_Los
    - UMa_Nlos
    - UMi_Los
    - UMi_Nlos
    batch_size: 32
    noise_spectral_density: -174.0
    subcarrier_spacing: 120.0
    transmit_power: 30.0
    distance_range:
    - 10.0
    - 500.0
    carrier_freq: 28.0
    mod_order: 64
    ref_conf_dict:
      dmrs:
      - 0
      - 3072
      - 6
    fft_size: 4096
    num_guard_subcarriers: 1024
    num_symbol: 14
    cp_length: 590
    max_random_tap_delay_cp_proportion: 0.2
    rnd_seed: 0
    num_workers: 0
    is_phase_noise: false
    is_channel: true
    is_noise: true
training:
  desc: null
  value:
    lr: 0.0001
    weight_decay: 1.0e-06
    max_norm: 1.0
    num_iter: 1000000
    logging_step: 10
    evaluation_step: 1000
    evaluation_batch_size: 4
    pn_train_start_iter: 1000
    use_scheduler: false
    num_warmup_steps: 0
ch_estimation:
  desc: null
  value:
    cond:
      length: 3072
      in_channels: 2
      step_size: 12
      steps_per_token: 1
    transformer:
      length: 3072
      channels: 2
      num_layers: 4
      d_model: 128
      n_token: 256
      n_head: 8
      dim_feedforward: 1024
      dropout: 0.1
      activation: relu
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1754294163
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.17.8
      6: 4.44.2
      8:
      - 3
      - 5
      13: windows-amd64
